# Nim VM - Nim is very similiar to python and compiles to C, so it's got a speedy runtime.
# You may need to install the nim VS code extension to see this in wonderful syntax highlighting


#[
    !!
    I have removed memory management for now as the only things I can find on it is that it is 'managed by nim'. I'll do something about it tomorrow.
    Also yes I am perfectly aware that this code makes no sense and you're probably thinking what the fudge am I doing.
    I have a plan. I am also aware that that sounds very sketchy and unreliable...
    !! 
]#


# Parse file into various parts (Instruction, const, etc. pools)
let file2parse = readFile("somerandomfile")

for instructions in somerandomfile:
    case instructions:
        of NOP:
            ...
        of JMP:
            ...
        of JEZ:
            ...
        of JNZ:
            ...
        of JIE:
            ...
        of SWP:
            ...
        of YNK:
            ...
        of PP1:
            ...
        of PP2:
            ...
        of PP3:
            ...
        of PGV:
            ...
        of PGC:
            ...
        of PGA:
            ...
        of PK1:
            ...
        of PK2:
            ...
        of PK3:
            ...
        of PK4:
            ...
        of PK5:
            ...
        of PKN:
            ...
        of RZE:
            ...
        of CAL:
            ...
        of RET:
            ...