from .instruction import Instruction

class InstructionAFA(Instruction):
    def __init__(self): ...

class InstructionCAL(Instruction):
    def __init__(self, opcode: int): ...

class InstructionCFA(Instruction):
    def __init__(self, opcode: int): ...

class InstructionFLG(Instruction):
    def __init__(self, opcode: int): ...

class InstructionFPA(Instruction):
    def __init__(self): ...

class InstructionJEZ(Instruction):
    def __init__(self, opcode: int): ...

class InstructionJIE(Instruction):
    def __init__(self, opcode: int): ...

class InstructionJMP(Instruction):
    def __init__(self): ...

class InstructionJNZ(Instruction):
    def __init__(self): ...

class InstructionMVA(Instruction):
    def __init__(self, opcode: int): ...

class InstructionMVB(Instruction):
    def __init__(self, opcode: int): ...

class InstructionMVC(Instruction):
    def __init__(self): ...

class InstructionMVD(Instruction):
    def __init__(self, opcode: int): ...

class InstructionMVE(Instruction):
    def __init__(self): ...

class InstructionNOP(Instruction):
    def __init__(self): ...

class InstructionRET(Instruction):
    def __init__(self, opcode: int): ...

class InstructionRZE(Instruction):
    def __init__(self): ...
